"""Canonical names in an instance directory."""

MANIFEST_NAME = "kinby.toml"
ENV_NAME = ".env"
SYSTEM_NAME = "SYSTEM.md"
PERMISSIONS_NAME = "permissions.toml"
TOOLS_DIR = "tools"
SKILLS_DIR = "skills"
ROUTINES_DIR = "routines"
MEMORY_DIR = "memory"
PROFILE_NAME = "profile.md"
WORKSPACE_DIR = "workspace"
STATE_DIR = ".state"
GITIGNORE_NAME = ".gitignore"
