/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ClientFrame = CallFrame | SubscribeFrame | CancelFrame;
export type JsonValue = unknown;
export type ConfigActor = "app" | "agent" | "failure_policy";
export type FactoryName = string;
export type SetupValue = boolean | number | string;
/**
 * Where a setup field's value lands: the instance's configuration, or its secrets.
 */
export type SetupFieldKind = "config" | "secret";
/**
 * The instance file a package's configuration field lands in.
 */
export type TargetFile = "kinby.toml" | "package.yaml";
/**
 * How a client asks for a setup field's value, and so what the value is.
 */
export type SetupFieldType = "text" | "multiline" | "boolean" | "integer" | "choice" | "email" | "url";
/**
 * Where the factory the hub serves under a name comes from.
 */
export type FactorySource = "hub" | "shipped";
/**
 * How one attempt at a step ended.
 */
export type StepEnding = "clean" | "failed" | "interrupted";
export type StepId = string;
export type StepValue = boolean | number | string;
/**
 * Where a factory run stands.
 */
export type FactoryRunStatus = "running" | "queued" | "parked" | "needs-human" | "done" | "cancelled";
export type CommitSha = string;
/**
 * What an instance's contract server can do. A hub reads it before acting on the instance.
 */
export type Capability = "ws" | "drain";
/**
 * What an adoption preflight found. Each one is a decision the operator has to take.
 */
export type AdoptionFindingKind =
  | "previous-manager"
  | "legacy-runtime"
  | "unreachable"
  | "duplicate-adoption"
  | "storage-owned"
  | "retained-storage"
  | "invalid-instance"
  | "manifest-id-taken"
  | "retained-identity"
  | "package-mismatch";
/**
 * Who manages an existing container now, read from the labels it carries.
 */
export type ContainerOwner = "hub" | "other-hub" | "compose" | "unmanaged";
export type StorageKind = "bind" | "volume";
/**
 * A name from a fixed palette. A client maps each name to colors of its own theme.
 */
export type AvatarColor = "blue" | "violet" | "green" | "amber" | "red" | "gray";
export type AvatarShape = "circle" | "squircle" | "square";
/**
 * How an instance's accepted work ended when it drained.
 */
export type DrainState = "drained" | "interrupted";
export type IntendedState = "stopped" | "running" | "removed" | "deleted";
export type ProcessState = "missing" | "created" | "starting" | "running" | "stopped" | "failed" | "unavailable";
/**
 * A change a running instance applies only once it is recreated.
 */
export type RecreateReason = "secrets" | "package_config";
export type Readiness = "not-running" | "starting" | "ready" | "unhealthy" | "unknown";
/**
 * How an instance's subscription login stands: not signed in yet, or how its last one ended.
 */
export type LoginState = "pending" | "signed_in" | "failed";
export type PriceSource = "shipped" | "manifest";
/**
 * When kinby asks the user to rate a completed turn.
 */
export type FeedbackPolicy = "every-turn" | "off";
/**
 * When kinby writes a model-assisted recap.
 */
export type RecapPolicy = "every-turn" | "off";
export type NodeKind = "fact" | "episode";
/**
 * Where a knowledge graph node came from. The instance derives it from the node's file.
 */
export type NodeSource = "agent" | "recap" | "user";
export type OperationKind =
  | "create"
  | "start"
  | "stop"
  | "secrets"
  | "recreate"
  | "adopt"
  | "update"
  | "remove"
  | "restore"
  | "delete"
  | "prepare"
  | "login";
export type OperationState = "pending" | "running" | "succeeded" | "failed";
export type PermissionMode = "read-only" | "ask" | "auto" | "full-access";
/**
 * What the gate answers for a tool call, and the rule a tool can be given in its place.
 */
export type GateAction = "allow" | "ask" | "deny";
export type PromptName = "behavior" | "recap";
export type RoutineRunOutcome = "running" | "parked" | "work" | "no-work" | "failed" | "interrupted";
export type RoutineNoticeKind = "first-failure" | "disabled";
export type SignalAuth = "token" | "hmac-sha256";
/**
 * Where a skill comes from, in the order the model looks for it.
 */
export type SkillTier = "instance" | "package" | "workspace";
export type StatsBucketSize = "day" | "week";
export type UsageSource = "api" | "claude-subscription" | "chatgpt-subscription";
export type TurnClosingKind = "completed" | "failed" | "interrupted";
export type DelegatedRunOutcome = "completed" | "failed" | "limited";
export type RoutineTrigger = "scheduled" | "manual" | "catch-up" | "signal";
export type CompletionOutcome = "work" | "no-work";
export type TurnVerdict = "good" | "bad";
export type HookName = string;
export type ToolName = string;
export type ApprovalDecision = "approve" | "deny";
export type ThreadStatus = "idle" | "running" | "awaiting_approval" | "failed";
export type ThreadFilter = "sidebar" | "all" | "archived";
export type ChangeStatus = "added" | "modified" | "deleted" | "renamed";
/**
 * What the gate does with a tool: its own rule in permissions.toml, or the mode's.
 */
export type ToolRule = "allow" | "ask" | "deny" | "mode";
export type ServerFrame = ResultFrame | ErrorFrame | SubscribedFrame | ItemFrame | EndFrame;
export type ErrorCode =
  | "NOT_FOUND"
  | "THREAD_BUSY"
  | "INSTANCE_BUSY"
  | "INSTANCE_DRAINING"
  | "TURN_OPEN"
  | "NO_ACTIVE_TURN"
  | "PARKED_TURN_UNAVAILABLE"
  | "PERMISSION_DENIED"
  | "BUDGET_EXCEEDED"
  | "MODEL_UNPRICED"
  | "SNAPSHOT_UNAVAILABLE"
  | "RESOURCE_EXHAUSTED"
  | "INVALID_ARGUMENT"
  | "NOT_PREPARED"
  | "INVALID_SETUP"
  | "STALE"
  | "ROUTINE_PENDING"
  | "CONNECTION_LOST"
  | "INTERNAL";
export type GateOutcome = "allow" | "deny";
export type GateDecider = "policy" | "user";

export interface Contract {
  client_frame: ClientFrame;
  methods: {
    "config.history": {
      command: ConfigHistoryCommand;
      result: ConfigHistoryResult;
    };
    "factory.check": {
      command: FactoryCheckCommand;
      result: FactoryCheckResult;
    };
    "factory.describe": {
      command: FactoryDescribeCommand;
      result: FactoryDescription;
    };
    "factory.edit": {
      command: FactoryEditCommand;
      result: FactoryResult;
    };
    "factory.get": {
      command: FactoryGetCommand;
      result: FactoryResult;
    };
    "factory.install": {
      command: FactoryInstallCommand;
      result: FactoryInstallResult;
    };
    "factory.list": {
      command: FactoryListCommand;
      result: FactoryListResult;
    };
    "factory.remove": {
      command: FactoryRemoveCommand;
      result: FactoryRemoveResult;
    };
    "factory.run.get": {
      command: FactoryRunGetCommand;
      result: FactoryRunDetail;
    };
    "factory.run.intake": {
      command: FactoryRunIntakeCommand;
      result: FactoryRun;
    };
    "factory.run.list": {
      command: FactoryRunListCommand;
      result: FactoryRunListResult;
    };
    "image.prepare": {
      command: ImagePrepareCommand;
      result: ImagePrepareResult;
    };
    "instance.adopt": {
      command: InstanceAdoptCommand;
      result: LifecycleOperationResult;
    };
    "instance.adopt.preview": {
      command: InstanceAdoptPreviewCommand;
      result: InstanceAdoptPreviewResult;
    };
    "instance.create": {
      command: InstanceCreateCommand;
      result: LifecycleOperationResult;
    };
    "instance.delete": {
      command: InstanceDeleteCommand;
      result: LifecycleOperationResult;
    };
    "instance.delete.preview": {
      command: InstanceDeletePreviewCommand;
      result: InstanceDeletePreviewResult;
    };
    "instance.drain": {
      command: InstanceDrainCommand;
      result: InstanceDrainResult;
    };
    "instance.list": {
      command: InstanceListCommand;
      result: InstanceListResult;
    };
    "instance.login.start": {
      command: InstanceLoginStartCommand;
      result: LifecycleOperationResult;
    };
    "instance.logs": {
      command: InstanceLogsCommand;
      result: InstanceLogsResult;
    };
    "instance.probe": {
      command: InstanceProbeCommand;
      result: InstanceProbeResult;
    };
    "instance.recreate": {
      command: InstanceRecreateCommand;
      result: LifecycleOperationResult;
    };
    "instance.remove": {
      command: InstanceRemoveCommand;
      result: LifecycleOperationResult;
    };
    "instance.restore": {
      command: InstanceRestoreCommand;
      result: LifecycleOperationResult;
    };
    "instance.secrets.set": {
      command: InstanceSecretsSetCommand;
      result: LifecycleOperationResult;
    };
    "instance.start": {
      command: InstanceStartCommand;
      result: LifecycleOperationResult;
    };
    "instance.status": {
      command: InstanceStatusCommand;
      result: InstanceStatusResult;
    };
    "instance.stop": {
      command: InstanceStopCommand;
      result: LifecycleOperationResult;
    };
    "instance.update": {
      command: InstanceUpdateCommand;
      result: LifecycleOperationResult;
    };
    "manifest.get": {
      command: ManifestGetCommand;
      result: ManifestResult;
    };
    "manifest.set": {
      command: ManifestSetCommand;
      result: ManifestResult;
    };
    "memory.add": {
      command: MemoryAddCommand;
      result: MemoryWriteResult;
    };
    "memory.correct": {
      command: MemoryCorrectCommand;
      result: MemoryWriteResult;
    };
    "memory.forget": {
      command: MemoryForgetCommand;
      result: MemoryForgetResult;
    };
    "memory.list": {
      command: MemoryListCommand;
      result: MemoryListResult;
    };
    "memory.open": {
      command: MemoryOpenCommand;
      result: MemoryOpenResult;
    };
    "operation.get": {
      command: OperationGetCommand;
      result: OperationGetResult;
    };
    "package.config.get": {
      command: PackageConfigGetCommand;
      result: PackageConfigResult;
    };
    "package.config.set": {
      command: PackageConfigSetCommand;
      result: PackageConfigResult;
    };
    "package.describe": {
      command: PackageDescribeCommand;
      result: PackageDescription;
    };
    "package.list": {
      command: PackageListCommand;
      result: PackageListResult;
    };
    "permissions.get": {
      command: PermissionsGetCommand;
      result: PermissionsResult;
    };
    "permissions.set": {
      command: PermissionsSetCommand;
      result: PermissionsResult;
    };
    "profile.get": {
      command: ProfileGetCommand;
      result: ProfileResult;
    };
    "profile.set": {
      command: ProfileSetCommand;
      result: ProfileResult;
    };
    "prompt.get": {
      command: PromptGetCommand;
      result: PromptResult;
    };
    "prompt.set": {
      command: PromptSetCommand;
      result: PromptResult;
    };
    "routine.delete": {
      command: RoutineDeleteCommand;
      result: RoutineDeleteResult;
    };
    "routine.list": {
      command: RoutineListCommand;
      result: RoutineListResult;
    };
    "routine.read": {
      command: RoutineReadCommand;
      result: RoutineFile;
    };
    "routine.rename": {
      command: RoutineRenameCommand;
      result: RoutineFile;
    };
    "routine.run": {
      command: RoutineRunCommand;
      result: AcceptedResult;
    };
    "routine.set_enabled": {
      command: RoutineSetEnabledCommand;
      result: RoutineFile;
    };
    "routine.write": {
      command: RoutineWriteCommand;
      result: RoutineFile;
    };
    "skill.customize": {
      command: SkillCustomizeCommand;
      result: SkillResult;
    };
    "skill.delete": {
      command: SkillDeleteCommand;
      result: SkillListResult;
    };
    "skill.list": {
      command: SkillListCommand;
      result: SkillListResult;
    };
    "skill.read": {
      command: SkillReadCommand;
      result: SkillResult;
    };
    "skill.write": {
      command: SkillWriteCommand;
      result: SkillResult;
    };
    "stats.get": {
      command: StatsGetCommand;
      result: StatsGetResult;
    };
    "stats.summary": {
      command: StatsGetCommand;
      result: StatsSummaryResult;
    };
    "step.run": {
      command: StepRunCommand;
      result: StepResult;
    };
    "thread.approval.respond": {
      command: ThreadApprovalRespondCommand;
      result: AcceptedResult;
    };
    "thread.archive": {
      command: ThreadArchiveCommand;
      result: ThreadSummary;
    };
    "thread.create": {
      command: ThreadCreateCommand;
      result: ThreadCreateResult;
    };
    "thread.list": {
      command: ThreadListCommand;
      result: ThreadListResult;
    };
    "thread.mode.set": {
      command: ThreadModeSetCommand;
      result: AcceptedResult;
    };
    "thread.rename": {
      command: ThreadRenameCommand;
      result: ThreadSummary;
    };
    "thread.turn.diff": {
      command: ThreadTurnDiffCommand;
      result: ThreadTurnDiffResult;
    };
    "thread.turn.interrupt": {
      command: ThreadTurnInterruptCommand;
      result: AcceptedResult;
    };
    "thread.turn.list": {
      command: ThreadTurnListCommand;
      result: ThreadTurnListResult;
    };
    "thread.turn.rate": {
      command: ThreadTurnRateCommand;
      result: AcceptedResult;
    };
    "thread.turn.revert": {
      command: ThreadTurnRevertCommand;
      result: AcceptedResult;
    };
    "thread.turn.revert.preview": {
      command: ThreadTurnRevertPreviewCommand;
      result: ThreadTurnRevertPreviewResult;
    };
    "thread.turn.start": {
      command: ThreadTurnStartCommand;
      result: AcceptedResult;
    };
    "thread.turn.target.list": {
      command: ThreadTurnTargetListCommand;
      result: ThreadTurnTargetListResult;
    };
    "thread.unarchive": {
      command: ThreadUnarchiveCommand;
      result: ThreadSummary;
    };
    "tool.list": {
      command: ToolListCommand;
      result: ToolListResult;
    };
    "usage.get": {
      command: UsageGetCommand;
      result: UsageGetResult;
    };
  };
  server_frame: ServerFrame;
  subscriptions: {
    "factory.run.subscribe": {
      command: FactoryRunSubscribeCommand;
      item: FactoryRun;
    };
    "thread.subscribe": {
      command: ThreadSubscribeCommand;
      item: Event;
    };
  };
}
export interface CallFrame {
  id: string;
  method: string;
  params?: {
    [k: string]: JsonValue;
  };
  type: "call";
}
export interface SubscribeFrame {
  id: string;
  method: string;
  params?: {
    [k: string]: JsonValue;
  };
  type: "subscribe";
}
export interface CancelFrame {
  id: string;
  type: "cancel";
}
export interface ConfigHistoryCommand {
  file?: string | null;
  limit: number;
}
export interface ConfigHistoryResult {
  changes: ConfigChange[];
}
/**
 * One recorded edit to the instance's configuration.
 */
export interface ConfigChange {
  actor: ConfigActor;
  at: string;
  diff: string;
  file: string;
  hash?: string | null;
  thread_id?: string | null;
  turn_id?: string | null;
}
export interface FactoryCheckCommand {
  name: FactoryName;
}
export interface FactoryCheckResult {
  problems: string[];
}
export interface FactoryDescribeCommand {
  name: FactoryName;
}
export interface FactoryDescription {
  instances: {
    [k: string]: DeclaredSetup;
  };
}
/**
 * The setup fields an instance asks for, the built-in fields first, and its logins.
 */
export interface DeclaredSetup {
  logins?: SubscriptionLogin[];
  setup_fields: SetupField[];
}
/**
 * One sign-in a package or a template declares, run in a setup container (ADR 0065).
 */
export interface SubscriptionLogin {
  command: string[];
  description: string;
  id: string;
  label: string;
  prompt_pattern: string;
  volume: string;
}
/**
 * One value a prepared image or an instance template asks for before an instance exists.
 */
export interface SetupField {
  choices?: string[] | null;
  default?: SetupValue | null;
  description: string;
  kind: SetupFieldKind;
  label: string;
  name: string;
  required: boolean;
  target?: SetupTarget | null;
  type: SetupFieldType;
}
/**
 * Where a configuration value lands: a file, and a dotted key inside it.
 */
export interface SetupTarget {
  file: TargetFile;
  key: string;
}
/**
 * Write files of a factory's folder at once. The hub keeps them only if the check passes.
 *
 * A shipped factory is never written: the edit lands on its copy in the hub's factories.
 */
export interface FactoryEditCommand {
  files: {
    [k: string]: string;
  };
  hash: string | null;
  name: FactoryName;
}
export interface FactoryResult {
  files: {
    [k: string]: string;
  };
  hash: string;
  name: FactoryName;
  source: FactorySource;
}
export interface FactoryGetCommand {
  name: FactoryName;
}
/**
 * Create each of the factory's instances from its template, once the factory check passes.
 */
export interface FactoryInstallCommand {
  instances: {
    [k: string]: FactoryInstanceSetup;
  };
  name: FactoryName;
}
/**
 * The setup values for one of the factory's instances, checked against its template.
 */
export interface FactoryInstanceSetup {
  config?: {
    [k: string]: SetupValue;
  };
  model: string;
  secrets?: {
    [k: string]: string;
  };
}
export interface FactoryInstallResult {
  instances: {
    [k: string]: LifecycleOperationResult;
  };
}
export interface LifecycleOperationResult {
  instance_id: string;
  operation_id: string;
}
export interface FactoryListCommand {}
export interface FactoryListResult {
  factories: FactorySummary[];
}
export interface FactorySummary {
  name: FactoryName;
  source: FactorySource;
}
/**
 * Remove each of the factory's active instances. Their data and records stay behind.
 */
export interface FactoryRemoveCommand {
  name: FactoryName;
}
export interface FactoryRemoveResult {
  instances: {
    [k: string]: LifecycleOperationResult;
  };
}
export interface FactoryRunGetCommand {
  run_id: string;
}
export interface FactoryRunDetail {
  attempts: StepAttempt[];
  run: FactoryRun;
}
/**
 * One attempt at one step of a factory run.
 */
export interface StepAttempt {
  attempt: number;
  ended_at: string | null;
  ending: StepEnding | null;
  outcome: string | null;
  started_at: string;
  step: StepId;
  summary: string;
  values: {
    [k: string]: StepValue;
  };
}
/**
 * One work item's trip through a factory's steps.
 */
export interface FactoryRun {
  created_at: string;
  factory: FactoryName;
  run_id: string;
  status: FactoryRunStatus;
  step: StepId | null;
  updated_at: string;
  work_item: {
    [k: string]: StepValue;
  };
}
/**
 * Hand a work item to the factory whose intake is this instance and routine.
 *
 * A work item that matches an unfinished run of the factory returns that run instead.
 */
export interface FactoryRunIntakeCommand {
  routine: string;
  work_item: {
    [k: string]: StepValue;
  };
}
export interface FactoryRunListCommand {
  factory: FactoryName;
  status?: FactoryRunStatus | null;
}
export interface FactoryRunListResult {
  runs: FactoryRun[];
}
/**
 * Prepare a package selection's image. No package prepares kinby's base image.
 */
export interface ImagePrepareCommand {
  package: PackageSelection | null;
}
export interface PackageSelection {
  distribution: string;
  id: string;
  image_recipe?: string;
  version: string | PackageCommit;
}
/**
 * One commit of a package's git repository, installed in place of an index version.
 */
export interface PackageCommit {
  sha: CommitSha;
  url: string;
}
export interface ImagePrepareResult {
  operation_id: string;
}
/**
 * Take ownership. The preflight runs again here, and a blocking finding stops it.
 */
export interface InstanceAdoptCommand {
  acknowledge_interrupting_stop?: boolean;
  claim_signals?: boolean;
  package?: PackageSelection | null;
  path: string;
  relinquished?: boolean;
  runtime_id: string;
}
/**
 * Preview an adoption. It reads the instance and its container and changes neither.
 */
export interface InstanceAdoptPreviewCommand {
  acknowledge_interrupting_stop?: boolean;
  package?: PackageSelection | null;
  path: string;
  relinquished?: boolean;
  runtime_id: string;
}
/**
 * What the hub would take over, and what stands in the way of taking it.
 */
export interface InstanceAdoptPreviewResult {
  capabilities: Capability[];
  findings: AdoptionFinding[];
  handoff: AdoptionHandoff;
  image_id: string;
  instance_id: string;
  manifest_id: string;
  owner: ContainerOwner;
  owner_name: string;
  path: string;
  persona_name: string | null;
  runtime_id: string;
  storage: StorageItem[];
}
/**
 * One observation of the preflight. A blocking finding stops the handoff.
 */
export interface AdoptionFinding {
  blocking: boolean;
  detail: string;
  kind: AdoptionFindingKind;
}
/**
 * What the handoff costs and what the operator does first. The hub rewrites no Compose file.
 */
export interface AdoptionHandoff {
  downtime: string;
  signals: string;
  steps: string[];
}
export interface StorageItem {
  destination: string;
  kind: StorageKind;
  source: string;
  writable: boolean;
}
export interface InstanceCreateCommand {
  avatar?: Avatar;
  config?: {
    [k: string]: SetupValue;
  };
  manifest_id: string;
  model: string;
  package?: PackageSelection | null;
  persona_name?: string | null;
  revision?: string;
  secrets?: {
    [k: string]: string;
  };
}
/**
 * How a client draws an instance. The hub keeps it, not the instance directory.
 */
export interface Avatar {
  color: AvatarColor;
  shape: AvatarShape;
}
/**
 * Delete the previewed targets. A target that changed since the preview stops it.
 */
export interface InstanceDeleteCommand {
  directories: string[];
  instance_id: string;
  volumes: string[];
}
/**
 * Preview a removed instance's permanent deletion. It reads the retained inventory only.
 */
export interface InstanceDeletePreviewCommand {
  instance_id: string;
}
/**
 * Exactly what a deletion removes: the removed instance's owned directories and volumes.
 */
export interface InstanceDeletePreviewResult {
  directories: string[];
  instance_id: string;
  volumes: string[];
}
export interface InstanceDrainCommand {
  force?: boolean;
}
export interface InstanceDrainResult {
  state: DrainState;
}
export interface InstanceListCommand {
  removed?: boolean;
}
export interface InstanceListResult {
  instances: InstanceSummary[];
}
export interface InstanceSummary {
  avatar: Avatar;
  detail?: string;
  factory?: FactoryName | null;
  image_id: string;
  instance_id: string;
  intended_state: IntendedState;
  manifest_id: string;
  notices: (RevisionBehind | PackageTemplateOlder)[];
  package?: PackageSummary | null;
  persona_name: string | null;
  process: ProcessState;
  runtime_id: string;
  setup_pending: boolean;
  source_revision: string;
  storage: StorageItem[];
}
/**
 * The instance runs another kinby revision than the hub's checkout, so an update is there.
 */
export interface RevisionBehind {
  code: "revision_behind";
  hub_revision: string;
  instance_revision: string;
  message: string;
}
/**
 * The instance's configuration was copied from another version of its installed package.
 */
export interface PackageTemplateOlder {
  code: "package_template_older";
  initialized_version: string;
  installed_version: string;
  message: string;
}
export interface PackageSummary {
  distribution: string;
  id: string;
  version: string | PackageCommit;
}
/**
 * Run one of the instance's subscription logins in a setup container.
 */
export interface InstanceLoginStartCommand {
  instance_id: string;
  login_id: string;
}
export interface InstanceLogsCommand {
  instance_id: string;
  tail?: number | null;
}
export interface InstanceLogsResult {
  instance_id: string;
  text: string;
}
export interface InstanceProbeCommand {}
export interface InstanceProbeResult {
  capabilities: Capability[];
  contract_version: string;
  restart_reasons?: RecreateReason[];
}
export interface InstanceRecreateCommand {
  instance_id: string;
}
/**
 * Drain and remove one instance's container. Its data and its record stay behind.
 */
export interface InstanceRemoveCommand {
  instance_id: string;
}
/**
 * Bring a removed instance back from its retained record, stopped.
 */
export interface InstanceRestoreCommand {
  instance_id: string;
}
/**
 * Replace the named values in one instance's secrets. The result carries none of them back.
 */
export interface InstanceSecretsSetCommand {
  instance_id: string;
  secrets: {
    [k: string]: string;
  };
}
export interface InstanceStartCommand {
  instance_id: string;
}
export interface InstanceStatusCommand {
  instance_id: string;
}
export interface InstanceStatusResult {
  active_operation_id?: string | null;
  detail?: string;
  instance_id: string;
  process: ProcessState;
  readiness: Readiness;
  recreate_reasons: RecreateReason[];
  setup: InstanceSetup;
}
/**
 * What an instance declares it needs, as its stored descriptor has it, and what is done.
 */
export interface InstanceSetup {
  logins: LoginSetup[];
  secrets: SecretSetup[];
}
/**
 * One subscription login an instance declares, its state, and its sign-in while one runs.
 */
export interface LoginSetup {
  description: string;
  id: string;
  label: string;
  operation_id?: string | null;
  state: LoginState;
}
/**
 * One secret field an instance declares, and whether it holds a value. Never the value.
 */
export interface SecretSetup {
  is_set: boolean;
  label: string;
  name: string;
  required: boolean;
  variable: string | null;
}
export interface InstanceStopCommand {
  force?: boolean;
  instance_id: string;
}
/**
 * Move one instance to the image a revision prepares.
 *
 * Its package selection travels along, moved to another commit when a pin names one.
 */
export interface InstanceUpdateCommand {
  instance_id: string;
  package?: PackagePin | null;
  revision: string;
}
/**
 * Move an instance's package to another commit of the git repository it comes from.
 *
 * It names the package it moves, which must be the instance's own (ADR 0040).
 */
export interface PackagePin {
  id: string;
  image_recipe?: string | null;
  sha: CommitSha;
}
export interface ManifestGetCommand {}
export interface ManifestResult {
  hash: string;
  model_choices: ModelChoice[];
  values: ManifestValues;
}
/**
 * A model the budget can count, because kinby ships its price or the manifest sets one.
 */
export interface ModelChoice {
  key_set: boolean;
  model: string;
  priced_from: PriceSource;
}
/**
 * The fields of ``kinby.toml`` a client may change. The hub owns the rest.
 */
export interface ManifestValues {
  budgets: ManifestBudgets;
  feedback: ManifestFeedback;
  memory: ManifestMemory;
  models: ManifestModels;
  persona_name: string | null;
  routines: ManifestRoutines;
  tools: ManifestTools;
}
export interface ManifestBudgets {
  seconds: number | null;
  steps: number | null;
  tokens: number | null;
  usd_per_day: number | null;
}
export interface ManifestFeedback {
  ask: FeedbackPolicy;
}
export interface ManifestMemory {
  recap: RecapPolicy;
}
export interface ManifestModels {
  embed: string | null;
  main: string;
  recap: string | null;
}
export interface ManifestRoutines {
  timezone: string;
}
export interface ManifestTools {
  bash_timeout_seconds: number;
  defaults: boolean;
}
export interface ManifestSetCommand {
  hash: string;
  prices?: {
    [k: string]: NewModelPrice;
  };
  values: ManifestValues;
}
export interface NewModelPrice {
  input: number;
  output: number;
}
export interface MemoryAddCommand {
  body: string;
  description: string;
  subjects: string[];
}
export interface MemoryWriteResult {
  node: string;
}
export interface MemoryCorrectCommand {
  body: string;
  description: string;
  node: string;
  subjects: string[];
}
export interface MemoryForgetCommand {
  node: string;
}
export interface MemoryForgetResult {}
export interface MemoryListCommand {
  after?: string | null;
  before?: string | null;
  cursor?: string | null;
  kind?: NodeKind | null;
  limit?: number;
  query?: string;
  subject?: string | null;
}
export interface MemoryListResult {
  cursor: string | null;
  items: NodeSummary[];
}
export interface NodeSummary {
  date: string;
  description: string;
  kind: NodeKind;
  node: string;
  source: NodeSource;
  subjects: string[];
}
export interface MemoryOpenCommand {
  node: string;
}
export interface MemoryOpenResult {
  body: string;
  date: string;
  description: string;
  kind: NodeKind;
  node: string;
  source: NodeSource;
  subjects: string[];
  thread: string | null;
  tools: string[] | null;
  turn: string | null;
}
export interface OperationGetCommand {
  operation_id: string;
}
export interface OperationGetResult {
  detail: string;
  instance_id: string | null;
  kind: OperationKind;
  operation_id: string;
  state: OperationState;
  steps?: OperationStep[];
}
/**
 * One named stage of a lifecycle operation, in the order the hub ran it.
 */
export interface OperationStep {
  detail: string;
  name: string;
  prompt?: LoginPrompt | null;
  state: OperationState;
}
/**
 * Where the user finishes a subscription login, and the one-time code they enter there.
 */
export interface LoginPrompt {
  code: string;
  url: string;
}
export interface PackageConfigGetCommand {}
export interface PackageConfigResult {
  hash: string;
  schema: {
    [k: string]: JsonValue;
  };
  values: {
    [k: string]: JsonValue;
  };
}
export interface PackageConfigSetCommand {
  hash: string;
  values: {
    [k: string]: JsonValue;
  };
}
/**
 * Read what a prepared selection declares. It never builds.
 */
export interface PackageDescribeCommand {
  package: PackageSelection | null;
}
/**
 * What a prepared image declares: its card, its version, its setup fields, and its logins.
 */
export interface PackageDescription {
  description: string;
  display_name: string;
  icon: string;
  logins?: SubscriptionLogin[];
  setup_fields: SetupField[];
  version: string;
}
export interface PackageListCommand {}
export interface PackageListResult {
  packages: CuratedPackage[];
}
/**
 * One package of the curated list: its card, and the selection a client prepares it with.
 *
 * The selection carries no image recipe. The hub adds the entry's recipe when it builds.
 */
export interface CuratedPackage {
  description: string;
  display_name: string;
  icon: string;
  id: string;
  selection: PackageSelection;
}
export interface PermissionsGetCommand {}
export interface PermissionsResult {
  bash: BashPermissions;
  ceiling: PermissionMode;
  hash: string;
  mode: PermissionMode;
  tools: {
    [k: string]: GateAction;
  };
}
export interface BashPermissions {
  ask: string[];
  deny: DenyPattern[];
}
export interface DenyPattern {
  pattern: string;
  shipped: boolean;
}
export interface PermissionsSetCommand {
  bash: OwnBashPatterns;
  ceiling: PermissionMode;
  hash: string;
  mode: PermissionMode;
  tools: {
    [k: string]: GateAction;
  };
}
export interface OwnBashPatterns {
  ask: string[];
  deny: string[];
}
export interface ProfileGetCommand {}
export interface ProfileResult {
  hash: string;
  text: string;
  tokens: number;
}
export interface ProfileSetCommand {
  hash: string;
  text: string;
}
export interface PromptGetCommand {
  name: PromptName;
}
export interface PromptResult {
  content: string;
  default: boolean;
  hash: string;
}
export interface PromptSetCommand {
  content: string;
  hash: string;
  name: PromptName;
}
export interface RoutineDeleteCommand {
  hash: string;
  name: string;
}
export interface RoutineDeleteResult {}
export interface RoutineListCommand {}
export interface RoutineListResult {
  routines: RoutineSummary[];
  warnings: Warning[];
}
export interface RoutineSummary {
  description: string;
  enabled: boolean;
  failure_count?: number;
  last_failure?: string | null;
  last_run: RoutineLastRun | null;
  mode: PermissionMode;
  name: string;
  next_run: string | null;
  notices?: RoutineNotice[];
  pending: number;
  schedule: string | null;
  signal?: SignalSummary | null;
}
export interface RoutineLastRun {
  first_line?: string;
  outcome: RoutineRunOutcome;
  started_at: string;
  thread_id: string;
  turn_id: string;
}
export interface RoutineNotice {
  kind: RoutineNoticeKind;
  message: string;
  thread_id: string;
  turn_id: string;
}
export interface SignalSummary {
  auth: SignalAuth;
  path: string;
}
export interface Warning {
  message: string;
  sources: string[];
  type: "warning";
}
export interface RoutineReadCommand {
  name: string;
}
export interface RoutineFile {
  content: string;
  hash: string;
  name: string;
}
export interface RoutineRenameCommand {
  hash: string;
  name: string;
  new_name: string;
}
export interface RoutineRunCommand {
  name: string;
  payload?: RoutinePayload | null;
}
export interface RoutinePayload {
  body: string;
  content_type: "application/json" | "text/plain";
}
export interface AcceptedResult {
  sequence: number;
  thread_id: string;
  turn_id: string;
}
export interface RoutineSetEnabledCommand {
  enabled: boolean;
  name: string;
}
export interface RoutineWriteCommand {
  content: string;
  hash: string | null;
  name: string;
}
/**
 * Copy the skill the model reads into the instance, where it can be edited.
 */
export interface SkillCustomizeCommand {
  name: string;
}
export interface SkillResult {
  content: string;
  files: string[];
  hash: string;
}
/**
 * Delete the instance copy, so the skill it hid, if any, applies again.
 */
export interface SkillDeleteCommand {
  hash: string;
  name: string;
}
export interface SkillListResult {
  skills: SkillSummary[];
  warnings: Warning[];
}
export interface SkillSummary {
  description: string;
  name: string;
  shadowed_by: SkillTier | null;
  source: string;
  tier: SkillTier;
}
export interface SkillListCommand {}
export interface SkillReadCommand {
  name: string;
  tier: SkillTier;
}
/**
 * Write the instance copy's ``SKILL.md``, creating the skill when ``hash`` is null.
 */
export interface SkillWriteCommand {
  content: string;
  hash: string | null;
  name: string;
}
export interface StatsGetCommand {
  by?: StatsBucketSize;
  since?: string | null;
  until?: string | null;
}
export interface StatsGetResult {
  buckets: StatsBucket[];
  limits: PlanLimit[];
  plan_use: PlanUse[];
  records: TurnMetrics[];
  total: StatsSummary;
  unpriced_models: string[];
  warnings?: ModelCallMismatch[];
}
export interface StatsBucket {
  approvals_requested: number;
  bad_ratings: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  completed: number;
  cost?: number | null;
  denies?: DenyCounts;
  failed: number;
  good_ratings: number;
  input_tokens: number;
  interrupted: number;
  mean_duration_seconds: number | null;
  memory_calls: MemoryCallCounts;
  navigation?: NavigationMeans;
  origins: OriginUse[];
  output_tokens: number;
  recap_input_tokens: number;
  recap_output_tokens: number;
  start: string;
  subscriptions: SubscriptionUse[];
  tool_calls: {
    [k: string]: number;
  };
  tool_duration?: ToolTime;
  turns_without_memory: number;
}
export interface DenyCounts {
  policy?: number;
  user?: number;
}
export interface MemoryCallCounts {
  forget?: number;
  open?: number;
  remember?: number;
  search?: number;
}
export interface NavigationMeans {
  duration_ms?: number | null;
  read_calls?: number | null;
  repeat_opens?: number | null;
  tokens_before_first_write?: number | null;
  turns?: number;
}
/**
 * The turns chat or one routine started, and what they cost and ran.
 *
 * A routine is keyed by the name its turns recorded, so a renamed routine has two rows.
 */
export interface OriginUse {
  cost: number | null;
  failed: number;
  no_work: number;
  origin: "user" | "routine";
  routine: string | null;
  runs: SourceRuns[];
  turns: number;
}
/**
 * The delegated runs one subscription usage source made.
 */
export interface SourceRuns {
  runs: number;
  usage_source: UsageSource;
}
/**
 * The delegated runs one subscription usage source paid for, counted and never priced.
 */
export interface SubscriptionUse {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  duration_ms?: number;
  input_tokens?: number;
  output_tokens?: number;
  runs?: number;
  usage_source: UsageSource;
}
export interface ToolTime {
  read_ms?: number;
  write_ms?: number;
}
/**
 * A subscription usage source whose plan stopped a delegated run, until its window resets.
 */
export interface PlanLimit {
  resets_at: string;
  usage_source: UsageSource;
}
/**
 * The runs a subscription usage source made in one plan window, up to now.
 */
export interface PlanUse {
  duration_seconds: number;
  runs: number;
  usage_source: UsageSource;
}
export interface TurnMetrics {
  approvals_requested: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  closed_at: string;
  closing_kind: TurnClosingKind;
  cost?: number | null;
  delegated_runs?: ReportedRun[];
  denies?: DenyCounts;
  duration_seconds: number | null;
  input_tokens: number;
  memory_calls: MemoryCallCounts;
  memory_consulted: boolean;
  memory_tokens: number;
  model: string | null;
  navigation?: Navigation;
  origin: (UserOrigin | RoutineOrigin) | null;
  outcome?: CompletionOutcome;
  output_tokens: number;
  prompt_version: string | null;
  rating: TurnRated | null;
  recap_input_tokens: number;
  recap_output_tokens: number;
  started_at: string | null;
  thread_id: string;
  tool_calls: {
    [k: string]: number;
  };
  tool_duration?: ToolTime;
  turn_id: string;
}
/**
 * A delegated run and the time it was recorded, which places it in a time range.
 */
export interface ReportedRun {
  run: DelegatedRun;
  timestamp: string;
}
/**
 * One run of an outside agent that a tool started, with that run's own tokens.
 *
 * A client that reports a running total across resumes, like a Codex thread, needs its
 * previous reading subtracted. Only a limited run has ``resets_at``: when its plan window resets.
 */
export interface DelegatedRun {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  client: string;
  client_turns: number;
  duration_ms: number;
  input_tokens: number;
  models: string[];
  outcome: DelegatedRunOutcome;
  output_tokens: number;
  resets_at?: string | null;
  usage_source: UsageSource;
}
export interface Navigation {
  distinct_paths?: number;
  duration_ms?: number;
  read_calls?: number;
  reads_before_first_write?: number;
  repeat_opens?: number;
  tokens_before_first_write?: number;
  write_calls?: number;
}
export interface UserOrigin {
  kind: "user";
}
export interface RoutineOrigin {
  delivery_id?: string | null;
  kind: "routine";
  name: string;
  trigger: RoutineTrigger;
}
export interface TurnRated {
  reason?: string | null;
  type: "turn.rated";
  verdict: TurnVerdict;
}
export interface StatsSummary {
  approvals_requested: number;
  bad_ratings: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  completed: number;
  cost?: number | null;
  denies?: DenyCounts;
  failed: number;
  good_ratings: number;
  input_tokens: number;
  interrupted: number;
  mean_duration_seconds: number | null;
  memory_calls: MemoryCallCounts;
  navigation?: NavigationMeans;
  origins: OriginUse[];
  output_tokens: number;
  recap_input_tokens: number;
  recap_output_tokens: number;
  subscriptions: SubscriptionUse[];
  tool_calls: {
    [k: string]: number;
  };
  tool_duration?: ToolTime;
  turns_without_memory: number;
}
export interface ModelCallMismatch {
  thread_id: string;
  turn_id: string;
}
/**
 * Usage across the hub's running instances, read live from each one and stored nowhere.
 *
 * A total leaves out every instance in ``skipped``, ``unreachable``, or ``outdated``.
 */
export interface StatsSummaryResult {
  api: ApiUse;
  buckets: {
    [k: string]: StatsBucket[];
  };
  limits: PlanLimit[];
  outdated: string[];
  plan_use: PlanUse[];
  skipped: string[];
  subscriptions: SubscriptionUse[];
  unreachable: string[];
}
/**
 * The model calls the API usage source paid for, priced where the model is known.
 */
export interface ApiUse {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  cost?: number | null;
  input_tokens: number;
  output_tokens: number;
}
/**
 * Run one step of a factory run in this instance, and return its result.
 */
export interface StepRunCommand {
  hook?: HookName | null;
  results?: {
    [k: string]: StepValue;
  };
  step: CommandStepRun | CodeStepRun;
  work_item: {
    [k: string]: StepValue;
  };
}
/**
 * Run each command in the instance's workspace without a shell, in order.
 *
 * The step passes when every command exits with code zero, and stops at the first that does not.
 */
export interface CommandStepRun {
  kind: "command";
  /**
   * @minItems 1
   */
  run: [string, ...string[]];
}
/**
 * Call one of the instance's tools, with no model turn around it.
 *
 * The tool's parameters named like a value of the run receive that value. A mapping the tool
 * returns is the step result's values.
 */
export interface CodeStepRun {
  call: ToolName;
  kind: "code";
}
/**
 * What one attempt at a step hands back to the hub.
 */
export interface StepResult {
  ending: StepEnding;
  outcome?: string | null;
  summary?: string;
  values?: {
    [k: string]: StepValue;
  };
}
export interface ThreadApprovalRespondCommand {
  approval_id: string;
  decision: ApprovalDecision;
  reason?: string | null;
  thread_id: string;
}
export interface ThreadArchiveCommand {
  thread_id: string;
}
export interface ThreadSummary {
  archived: boolean;
  created_at: string;
  id: string;
  last_activity_at: string;
  mode: PermissionMode;
  mode_pinned: boolean;
  origin: UserOrigin | RoutineOrigin;
  status: ThreadStatus;
  title: string | null;
}
export interface ThreadCreateCommand {
  title?: string | null;
}
export interface ThreadCreateResult {
  created_at: string;
  id: string;
}
export interface ThreadListCommand {
  cursor?: ThreadCursor | null;
  filter?: ThreadFilter;
  limit?: number | null;
  routine?: string | null;
}
/**
 * Where a page of threads ends: its last thread's activity and id, which the list sorts by.
 */
export interface ThreadCursor {
  id: string;
  last_activity_at: string;
}
export interface ThreadListResult {
  ceiling: PermissionMode;
  cursor: ThreadCursor | null;
  threads: ThreadSummary[];
}
export interface ThreadModeSetCommand {
  mode: PermissionMode;
  thread_id: string;
}
export interface ThreadRenameCommand {
  thread_id: string;
  title: string;
}
export interface ThreadTurnDiffCommand {
  thread_id: string;
  turn_id: string;
}
export interface ThreadTurnDiffResult {
  after: string;
  before: string;
  files: FileChange[];
  patch: string;
  turn_id: string;
}
export interface FileChange {
  additions: number;
  deletions: number;
  path: string;
  status: ChangeStatus;
}
export interface ThreadTurnInterruptCommand {
  thread_id: string;
}
export interface ThreadTurnListCommand {
  thread_id: string;
}
export interface ThreadTurnListResult {
  turn_ids: string[];
}
export interface ThreadTurnRateCommand {
  reason?: string | null;
  thread_id: string;
  turn_id: string;
  verdict: TurnVerdict;
}
export interface ThreadTurnRevertCommand {
  thread_id: string;
  turn_id: string;
}
export interface ThreadTurnRevertPreviewCommand {
  thread_id: string;
  turn_id: string;
}
export interface ThreadTurnRevertPreviewResult {
  files: FileChange[];
  turn_id: string;
}
export interface ThreadTurnStartCommand {
  message: string;
  thread_id: string;
}
export interface ThreadTurnTargetListCommand {
  thread_id: string;
}
export interface ThreadTurnTargetListResult {
  targets: TurnTarget[];
}
/**
 * One turn or workspace revert that a workspace operation can target.
 */
export interface TurnTarget {
  closed: boolean;
  turn_id: string;
}
export interface ThreadUnarchiveCommand {
  thread_id: string;
}
export interface ToolListCommand {}
export interface ToolListResult {
  tools: ToolSummary[];
  warnings: Warning[];
}
export interface ToolSummary {
  name: string;
  rule: ToolRule;
  source: string;
  write: boolean;
}
export interface UsageGetCommand {
  since?: string | null;
  until?: string | null;
}
export interface UsageGetResult {
  threads: ThreadUsage[];
}
export interface ThreadUsage {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  input_tokens: number;
  output_tokens: number;
  thread_id: string;
  turns: TurnUsage[];
}
export interface TurnUsage {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  delegated_runs?: ReportedRun[];
  input_tokens: number;
  output_tokens: number;
  recap_input_tokens: number;
  recap_output_tokens: number;
  turn_id: string;
}
export interface ResultFrame {
  id: string;
  result: {
    [k: string]: JsonValue;
  };
  type: "result";
}
/**
 * A frame the server could not read carries no id.
 */
export interface ErrorFrame {
  error: ErrorEnvelope;
  id?: string | null;
  type: "error";
}
export interface ErrorEnvelope {
  code: ErrorCode;
  fields?: {
    [k: string]: string;
  };
  message: string;
  retryable: boolean;
}
export interface SubscribedFrame {
  head_sequence: number;
  id: string;
  type: "subscribed";
}
export interface ItemFrame {
  id: string;
  item: {
    [k: string]: JsonValue;
  };
  type: "item";
}
export interface EndFrame {
  id: string;
  type: "end";
}
/**
 * Follow every factory run of the hub as its state changes. Nothing is replayed.
 */
export interface FactoryRunSubscribeCommand {}
export interface ThreadSubscribeCommand {
  after_sequence?: number;
  thread_id: string;
}
export interface Event {
  payload:
    | ModePinned
    | TurnStarted
    | MessageDelta
    | ModelCompleted
    | ToolCall
    | ToolGated
    | ToolResult
    | Warning
    | ApprovalRequested
    | TurnCompleted
    | TurnFailed
    | TurnInterrupted
    | TurnRated
    | RunDelegated
    | MemoryRecapped
    | RoutineFailureHandled
    | SignalReceived
    | WorkspaceReverted;
  sequence: number;
  thread_id: string;
  timestamp: string;
  turn_id: string;
}
export interface ModePinned {
  mode: PermissionMode;
  type: "mode.pinned";
}
export interface TurnStarted {
  message: string;
  model: string;
  origin?: UserOrigin | RoutineOrigin;
  permission_mode?: PermissionMode | null;
  prompt_version?: string | null;
  snapshot?: string | null;
  type: "turn.started";
}
export interface MessageDelta {
  text: string;
  type: "message.delta";
}
export interface ModelCompleted {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  duration_ms: number;
  input_tokens: number;
  model: string;
  output_tokens: number;
  type: "model.completed";
}
export interface ToolCall {
  arguments: {
    [k: string]: JsonValue;
  };
  call_id: string;
  name: string;
  type: "tool.call";
  write?: boolean | null;
}
export interface ToolGated {
  action: GateOutcome;
  call_id: string;
  decided_by: GateDecider;
  name: string;
  reason?: string | null;
  rule: string;
  type: "tool.gated";
}
export interface ToolResult {
  call_id: string;
  duration_ms?: number | null;
  error: boolean;
  name: string;
  output: string;
  type: "tool.result";
}
export interface ApprovalRequested {
  approval_id: string;
  arguments: {
    [k: string]: JsonValue;
  };
  name: string;
  rule: string;
  type: "approval.requested";
}
export interface TurnCompleted {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  input_tokens: number;
  outcome?: CompletionOutcome;
  output_tokens: number;
  snapshot?: string | null;
  type: "turn.completed";
}
export interface TurnFailed {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  code: ErrorCode;
  input_tokens?: number;
  message: string;
  output_tokens?: number;
  snapshot?: string | null;
  type: "turn.failed";
}
export interface TurnInterrupted {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  input_tokens?: number;
  output_tokens?: number;
  snapshot?: string | null;
  type: "turn.interrupted";
}
export interface RunDelegated {
  run: DelegatedRun;
  type: "run.delegated";
}
export interface MemoryRecapped {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  input_tokens: number;
  model?: string | null;
  node: string | null;
  output_tokens: number;
  type: "memory.recapped";
}
export interface RoutineFailureHandled {
  name: string;
  notice?: RoutineNotice | null;
  type: "routine.failure.handled";
}
export interface SignalReceived {
  delivery: Delivery;
  origin: RoutineOrigin;
  type: "signal.received";
}
export interface Delivery {
  body: string;
  content_type: string;
  delivery_id?: string | null;
  headers: {
    [k: string]: string;
  };
  received_at: string;
}
/**
 * The workspace went from ``previous`` back to ``restored``, the target's before tree.
 */
export interface WorkspaceReverted {
  previous: string;
  restored: string;
  target_turn_id: string;
  type: "workspace.reverted";
}
