/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ClientFrame = CallFrame | SubscribeFrame | CancelFrame;
export type JsonValue = unknown;
export type CommitSha = string;
/**
 * What an instance's contract server can do. A hub reads it before acting on the instance.
 */
export type Capability = "ws" | "drain";
/**
 * What an adoption preflight found. Each one is a decision the operator has to take.
 */
export type AdoptionFindingKind =
  | "previous-manager"
  | "legacy-runtime"
  | "unreachable"
  | "duplicate-adoption"
  | "storage-owned"
  | "retained-storage"
  | "invalid-instance"
  | "manifest-id-taken"
  | "retained-identity"
  | "package-mismatch";
/**
 * Who manages an existing container now, read from the labels it carries.
 */
export type ContainerOwner = "hub" | "other-hub" | "compose" | "unmanaged";
export type StorageKind = "bind" | "volume";
/**
 * How an instance's accepted work ended when it drained.
 */
export type DrainState = "drained" | "interrupted";
export type IntendedState = "stopped" | "running" | "removed" | "deleted";
export type ProcessState = "missing" | "created" | "starting" | "running" | "stopped" | "failed" | "unavailable";
export type Readiness = "not-running" | "starting" | "ready" | "unhealthy" | "unknown";
export type OperationKind =
  "create" | "start" | "stop" | "secrets" | "recreate" | "adopt" | "update" | "remove" | "restore" | "delete";
export type OperationState = "pending" | "running" | "succeeded" | "failed";
export type RoutineRunOutcome = "running" | "parked" | "work" | "no-work" | "failed" | "interrupted";
export type PermissionMode = "read-only" | "ask" | "auto" | "full-access";
export type RoutineNoticeKind = "first-failure" | "disabled";
export type SignalAuth = "token" | "hmac-sha256";
export type StatsBucketSize = "day" | "week";
export type UsageSource = "api" | "claude-subscription" | "chatgpt-subscription";
export type TurnClosingKind = "completed" | "failed" | "interrupted";
export type DelegatedRunOutcome = "completed" | "failed" | "limited";
export type TurnVerdict = "good" | "bad";
export type ChangeStatus = "added" | "modified" | "deleted" | "renamed";
export type ServerFrame = ResultFrame | ErrorFrame | SubscribedFrame | ItemFrame | EndFrame;
export type ErrorCode =
  | "NOT_FOUND"
  | "THREAD_BUSY"
  | "INSTANCE_BUSY"
  | "INSTANCE_DRAINING"
  | "TURN_OPEN"
  | "NO_ACTIVE_TURN"
  | "PARKED_TURN_UNAVAILABLE"
  | "PERMISSION_DENIED"
  | "BUDGET_EXCEEDED"
  | "MODEL_UNPRICED"
  | "SNAPSHOT_UNAVAILABLE"
  | "RESOURCE_EXHAUSTED"
  | "INVALID_ARGUMENT"
  | "CONNECTION_LOST"
  | "INTERNAL";
export type RoutineTrigger = "scheduled" | "manual" | "catch-up" | "signal";
export type GateOutcome = "allow" | "deny";
export type GateDecider = "policy" | "user";
export type CompletionOutcome = "work" | "no-work";

export interface Contract {
  client_frame: ClientFrame;
  methods: {
    "instance.adopt": {
      command: InstanceAdoptCommand;
      result: LifecycleOperationResult;
    };
    "instance.adopt.preview": {
      command: InstanceAdoptPreviewCommand;
      result: InstanceAdoptPreviewResult;
    };
    "instance.create": {
      command: InstanceCreateCommand;
      result: LifecycleOperationResult;
    };
    "instance.delete": {
      command: InstanceDeleteCommand;
      result: LifecycleOperationResult;
    };
    "instance.delete.preview": {
      command: InstanceDeletePreviewCommand;
      result: InstanceDeletePreviewResult;
    };
    "instance.drain": {
      command: InstanceDrainCommand;
      result: InstanceDrainResult;
    };
    "instance.list": {
      command: InstanceListCommand;
      result: InstanceListResult;
    };
    "instance.logs": {
      command: InstanceLogsCommand;
      result: InstanceLogsResult;
    };
    "instance.probe": {
      command: InstanceProbeCommand;
      result: InstanceProbeResult;
    };
    "instance.recreate": {
      command: InstanceRecreateCommand;
      result: LifecycleOperationResult;
    };
    "instance.remove": {
      command: InstanceRemoveCommand;
      result: LifecycleOperationResult;
    };
    "instance.restore": {
      command: InstanceRestoreCommand;
      result: LifecycleOperationResult;
    };
    "instance.secrets.set": {
      command: InstanceSecretsSetCommand;
      result: LifecycleOperationResult;
    };
    "instance.start": {
      command: InstanceStartCommand;
      result: LifecycleOperationResult;
    };
    "instance.status": {
      command: InstanceStatusCommand;
      result: InstanceStatusResult;
    };
    "instance.stop": {
      command: InstanceStopCommand;
      result: LifecycleOperationResult;
    };
    "instance.update": {
      command: InstanceUpdateCommand;
      result: LifecycleOperationResult;
    };
    "operation.get": {
      command: OperationGetCommand;
      result: OperationGetResult;
    };
    "routine.list": {
      command: RoutineListCommand;
      result: RoutineListResult;
    };
    "routine.run": {
      command: RoutineRunCommand;
      result: AcceptedResult;
    };
    "stats.get": {
      command: StatsGetCommand;
      result: StatsGetResult;
    };
    "thread.approval.respond": {
      command: ThreadApprovalRespondCommand;
      result: AcceptedResult;
    };
    "thread.create": {
      command: ThreadCreateCommand;
      result: ThreadCreateResult;
    };
    "thread.list": {
      command: ThreadListCommand;
      result: ThreadListResult;
    };
    "thread.mode.set": {
      command: ThreadModeSetCommand;
      result: AcceptedResult;
    };
    "thread.turn.diff": {
      command: ThreadTurnDiffCommand;
      result: ThreadTurnDiffResult;
    };
    "thread.turn.interrupt": {
      command: ThreadTurnInterruptCommand;
      result: AcceptedResult;
    };
    "thread.turn.list": {
      command: ThreadTurnListCommand;
      result: ThreadTurnListResult;
    };
    "thread.turn.rate": {
      command: ThreadTurnRateCommand;
      result: AcceptedResult;
    };
    "thread.turn.revert": {
      command: ThreadTurnRevertCommand;
      result: AcceptedResult;
    };
    "thread.turn.revert.preview": {
      command: ThreadTurnRevertPreviewCommand;
      result: ThreadTurnRevertPreviewResult;
    };
    "thread.turn.start": {
      command: ThreadTurnStartCommand;
      result: AcceptedResult;
    };
    "thread.turn.target.list": {
      command: ThreadTurnTargetListCommand;
      result: ThreadTurnTargetListResult;
    };
    "usage.get": {
      command: UsageGetCommand;
      result: UsageGetResult;
    };
  };
  server_frame: ServerFrame;
  subscriptions: {
    "thread.subscribe": {
      command: ThreadSubscribeCommand;
      item: Event;
    };
  };
}
export interface CallFrame {
  id: string;
  method: string;
  params?: {
    [k: string]: JsonValue;
  };
  type: "call";
}
export interface SubscribeFrame {
  id: string;
  method: string;
  params?: {
    [k: string]: JsonValue;
  };
  type: "subscribe";
}
export interface CancelFrame {
  id: string;
  type: "cancel";
}
/**
 * Take ownership. The preflight runs again here, and a blocking finding stops it.
 */
export interface InstanceAdoptCommand {
  acknowledge_interrupting_stop?: boolean;
  claim_signals?: boolean;
  package?: PackageSelection | null;
  path: string;
  relinquished?: boolean;
  runtime_id: string;
}
export interface PackageSelection {
  distribution: string;
  id: string;
  image_recipe?: string;
  version: string | PackageCommit;
}
/**
 * One commit of a package's git repository, installed in place of an index version.
 */
export interface PackageCommit {
  sha: CommitSha;
  url: string;
}
export interface LifecycleOperationResult {
  instance_id: string;
  operation_id: string;
}
/**
 * Preview an adoption. It reads the instance and its container and changes neither.
 */
export interface InstanceAdoptPreviewCommand {
  acknowledge_interrupting_stop?: boolean;
  package?: PackageSelection | null;
  path: string;
  relinquished?: boolean;
  runtime_id: string;
}
/**
 * What the hub would take over, and what stands in the way of taking it.
 */
export interface InstanceAdoptPreviewResult {
  capabilities: Capability[];
  findings: AdoptionFinding[];
  handoff: AdoptionHandoff;
  image_id: string;
  instance_id: string;
  manifest_id: string;
  owner: ContainerOwner;
  owner_name: string;
  path: string;
  persona_name: string | null;
  runtime_id: string;
  storage: StorageItem[];
}
/**
 * One observation of the preflight. A blocking finding stops the handoff.
 */
export interface AdoptionFinding {
  blocking: boolean;
  detail: string;
  kind: AdoptionFindingKind;
}
/**
 * What the handoff costs and what the operator does first. The hub rewrites no Compose file.
 */
export interface AdoptionHandoff {
  downtime: string;
  signals: string;
  steps: string[];
}
export interface StorageItem {
  destination: string;
  kind: StorageKind;
  source: string;
  writable: boolean;
}
export interface InstanceCreateCommand {
  manifest_id: string;
  model: string;
  package?: PackageSelection | null;
  persona_name?: string | null;
  revision?: string;
  secrets?: {
    [k: string]: string;
  };
}
/**
 * Delete the previewed targets. A target that changed since the preview stops it.
 */
export interface InstanceDeleteCommand {
  directories: string[];
  instance_id: string;
  volumes: string[];
}
/**
 * Preview a removed instance's permanent deletion. It reads the retained inventory only.
 */
export interface InstanceDeletePreviewCommand {
  instance_id: string;
}
/**
 * Exactly what a deletion removes: the removed instance's owned directories and volumes.
 */
export interface InstanceDeletePreviewResult {
  directories: string[];
  instance_id: string;
  volumes: string[];
}
export interface InstanceDrainCommand {
  force?: boolean;
}
export interface InstanceDrainResult {
  state: DrainState;
}
export interface InstanceListCommand {
  removed?: boolean;
}
export interface InstanceListResult {
  instances: InstanceSummary[];
}
export interface InstanceSummary {
  image_id: string;
  instance_id: string;
  intended_state: IntendedState;
  manifest_id: string;
  package?: PackageSummary | null;
  persona_name: string | null;
  runtime_id: string;
  source_revision: string;
  storage: StorageItem[];
}
export interface PackageSummary {
  distribution: string;
  id: string;
  version: string | PackageCommit;
}
export interface InstanceLogsCommand {
  instance_id: string;
  tail?: number | null;
}
export interface InstanceLogsResult {
  instance_id: string;
  text: string;
}
export interface InstanceProbeCommand {}
export interface InstanceProbeResult {
  capabilities: Capability[];
  contract_version: string;
}
export interface InstanceRecreateCommand {
  instance_id: string;
}
/**
 * Drain and remove one instance's container. Its data and its record stay behind.
 */
export interface InstanceRemoveCommand {
  instance_id: string;
}
/**
 * Bring a removed instance back from its retained record, stopped.
 */
export interface InstanceRestoreCommand {
  instance_id: string;
}
/**
 * Replace the named values in one instance's secrets. The result carries none of them back.
 */
export interface InstanceSecretsSetCommand {
  instance_id: string;
  secrets: {
    [k: string]: string;
  };
}
export interface InstanceStartCommand {
  instance_id: string;
}
export interface InstanceStatusCommand {
  instance_id: string;
}
export interface InstanceStatusResult {
  active_operation_id?: string | null;
  detail?: string;
  instance_id: string;
  process: ProcessState;
  readiness: Readiness;
}
export interface InstanceStopCommand {
  force?: boolean;
  instance_id: string;
}
/**
 * Move one instance to the image a revision prepares.
 *
 * Its package selection travels along, moved to another commit when a pin names one.
 */
export interface InstanceUpdateCommand {
  instance_id: string;
  package?: PackagePin | null;
  revision: string;
}
/**
 * Move an instance's package to another commit of the git repository it comes from.
 *
 * It names the package it moves, which must be the instance's own (ADR 0040).
 */
export interface PackagePin {
  id: string;
  image_recipe?: string | null;
  sha: CommitSha;
}
export interface OperationGetCommand {
  operation_id: string;
}
export interface OperationGetResult {
  detail: string;
  instance_id: string;
  kind: OperationKind;
  operation_id: string;
  state: OperationState;
  steps?: OperationStep[];
}
/**
 * One named stage of a lifecycle operation, in the order the hub ran it.
 */
export interface OperationStep {
  detail: string;
  name: string;
  state: OperationState;
}
export interface RoutineListCommand {}
export interface RoutineListResult {
  routines: RoutineSummary[];
  warnings: Warning[];
}
export interface RoutineSummary {
  description: string;
  enabled: boolean;
  failure_count?: number;
  last_failure?: string | null;
  last_run: RoutineLastRun | null;
  mode: PermissionMode;
  name: string;
  next_run: string | null;
  notices?: RoutineNotice[];
  pending: number;
  schedule: string | null;
  signal?: SignalSummary | null;
}
export interface RoutineLastRun {
  first_line?: string;
  outcome: RoutineRunOutcome;
  started_at: string;
  thread_id: string;
  turn_id: string;
}
export interface RoutineNotice {
  kind: RoutineNoticeKind;
  message: string;
  thread_id: string;
  turn_id: string;
}
export interface SignalSummary {
  auth: SignalAuth;
  path: string;
}
export interface Warning {
  message: string;
  sources: string[];
  type: "warning";
}
export interface RoutineRunCommand {
  name: string;
  payload?: RoutinePayload | null;
}
export interface RoutinePayload {
  body: string;
  content_type: "application/json" | "text/plain";
}
export interface AcceptedResult {
  sequence: number;
  thread_id: string;
  turn_id: string;
}
export interface StatsGetCommand {
  by?: StatsBucketSize;
  since?: string | null;
  until?: string | null;
}
export interface StatsGetResult {
  buckets: StatsBucket[];
  records: TurnMetrics[];
  total: StatsSummary;
  unpriced_models: string[];
  warnings?: ModelCallMismatch[];
}
export interface StatsBucket {
  approvals_requested: number;
  bad_ratings: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  completed: number;
  cost?: number | null;
  denies?: DenyCounts;
  failed: number;
  good_ratings: number;
  input_tokens: number;
  interrupted: number;
  mean_duration_seconds: number | null;
  memory_calls: MemoryCallCounts;
  navigation?: NavigationMeans;
  output_tokens: number;
  recap_input_tokens: number;
  recap_output_tokens: number;
  start: string;
  subscriptions: SubscriptionUse[];
  tool_calls: {
    [k: string]: number;
  };
  tool_duration?: ToolTime;
  turns_without_memory: number;
}
export interface DenyCounts {
  policy?: number;
  user?: number;
}
export interface MemoryCallCounts {
  forget?: number;
  open?: number;
  remember?: number;
  search?: number;
}
export interface NavigationMeans {
  duration_ms?: number | null;
  read_calls?: number | null;
  repeat_opens?: number | null;
  tokens_before_first_write?: number | null;
  turns?: number;
}
/**
 * The delegated runs one subscription usage source paid for, counted and never priced.
 */
export interface SubscriptionUse {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  duration_ms?: number;
  input_tokens?: number;
  output_tokens?: number;
  runs?: number;
  usage_source: UsageSource;
}
export interface ToolTime {
  read_ms?: number;
  write_ms?: number;
}
export interface TurnMetrics {
  approvals_requested: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  closed_at: string;
  closing_kind: TurnClosingKind;
  cost?: number | null;
  delegated_runs?: ReportedRun[];
  denies?: DenyCounts;
  duration_seconds: number | null;
  input_tokens: number;
  memory_calls: MemoryCallCounts;
  memory_consulted: boolean;
  memory_tokens: number;
  model: string | null;
  navigation?: Navigation;
  output_tokens: number;
  prompt_version: string | null;
  rating: TurnRated | null;
  recap_input_tokens: number;
  recap_output_tokens: number;
  started_at: string | null;
  thread_id: string;
  tool_calls: {
    [k: string]: number;
  };
  tool_duration?: ToolTime;
  turn_id: string;
}
/**
 * A delegated run and the time it was recorded, which places it in a time range.
 */
export interface ReportedRun {
  run: DelegatedRun;
  timestamp: string;
}
/**
 * One run of an outside agent that a tool started, with that run's own tokens.
 *
 * A client that reports a running total across resumes, like a Codex thread, needs its
 * previous reading subtracted. Only a limited run has ``resets_at``: when its plan window resets.
 */
export interface DelegatedRun {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  client: string;
  client_turns: number;
  duration_ms: number;
  input_tokens: number;
  models: string[];
  outcome: DelegatedRunOutcome;
  output_tokens: number;
  resets_at?: string | null;
  usage_source: UsageSource;
}
export interface Navigation {
  distinct_paths?: number;
  duration_ms?: number;
  read_calls?: number;
  reads_before_first_write?: number;
  repeat_opens?: number;
  tokens_before_first_write?: number;
  write_calls?: number;
}
export interface TurnRated {
  reason?: string | null;
  type: "turn.rated";
  verdict: TurnVerdict;
}
export interface StatsSummary {
  approvals_requested: number;
  bad_ratings: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  completed: number;
  cost?: number | null;
  denies?: DenyCounts;
  failed: number;
  good_ratings: number;
  input_tokens: number;
  interrupted: number;
  mean_duration_seconds: number | null;
  memory_calls: MemoryCallCounts;
  navigation?: NavigationMeans;
  output_tokens: number;
  recap_input_tokens: number;
  recap_output_tokens: number;
  subscriptions: SubscriptionUse[];
  tool_calls: {
    [k: string]: number;
  };
  tool_duration?: ToolTime;
  turns_without_memory: number;
}
export interface ModelCallMismatch {
  thread_id: string;
  turn_id: string;
}
export interface ThreadApprovalRespondCommand {
  answer: string;
  approval_id: string;
  thread_id: string;
}
export interface ThreadCreateCommand {
  title?: string | null;
}
export interface ThreadCreateResult {
  created_at: string;
  id: string;
}
export interface ThreadListCommand {}
export interface ThreadListResult {
  threads: ThreadSummary[];
}
export interface ThreadSummary {
  created_at: string;
  id: string;
  title: string | null;
}
export interface ThreadModeSetCommand {
  mode: PermissionMode;
  thread_id: string;
}
export interface ThreadTurnDiffCommand {
  thread_id: string;
  turn_id: string;
}
export interface ThreadTurnDiffResult {
  after: string;
  before: string;
  files: FileChange[];
  patch: string;
  turn_id: string;
}
export interface FileChange {
  additions: number;
  deletions: number;
  path: string;
  status: ChangeStatus;
}
export interface ThreadTurnInterruptCommand {
  thread_id: string;
}
export interface ThreadTurnListCommand {
  thread_id: string;
}
export interface ThreadTurnListResult {
  turn_ids: string[];
}
export interface ThreadTurnRateCommand {
  reason?: string | null;
  thread_id: string;
  turn_id: string;
  verdict: TurnVerdict;
}
export interface ThreadTurnRevertCommand {
  thread_id: string;
  turn_id: string;
}
export interface ThreadTurnRevertPreviewCommand {
  thread_id: string;
  turn_id: string;
}
export interface ThreadTurnRevertPreviewResult {
  files: FileChange[];
  turn_id: string;
}
export interface ThreadTurnStartCommand {
  message: string;
  thread_id: string;
}
export interface ThreadTurnTargetListCommand {
  thread_id: string;
}
export interface ThreadTurnTargetListResult {
  targets: TurnTarget[];
}
/**
 * One turn or workspace revert that a workspace operation can target.
 */
export interface TurnTarget {
  closed: boolean;
  turn_id: string;
}
export interface UsageGetCommand {
  since?: string | null;
  until?: string | null;
}
export interface UsageGetResult {
  threads: ThreadUsage[];
}
export interface ThreadUsage {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  input_tokens: number;
  output_tokens: number;
  thread_id: string;
  turns: TurnUsage[];
}
export interface TurnUsage {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  delegated_runs?: ReportedRun[];
  input_tokens: number;
  output_tokens: number;
  recap_input_tokens: number;
  recap_output_tokens: number;
  turn_id: string;
}
export interface ResultFrame {
  id: string;
  result: {
    [k: string]: JsonValue;
  };
  type: "result";
}
/**
 * A frame the server could not read carries no id.
 */
export interface ErrorFrame {
  error: ErrorEnvelope;
  id?: string | null;
  type: "error";
}
export interface ErrorEnvelope {
  code: ErrorCode;
  message: string;
  retryable: boolean;
}
export interface SubscribedFrame {
  head_sequence: number;
  id: string;
  type: "subscribed";
}
export interface ItemFrame {
  id: string;
  item: {
    [k: string]: JsonValue;
  };
  type: "item";
}
export interface EndFrame {
  id: string;
  type: "end";
}
export interface ThreadSubscribeCommand {
  after_sequence?: number;
  thread_id: string;
}
export interface Event {
  payload:
    | ModePinned
    | TurnStarted
    | MessageDelta
    | ModelCompleted
    | ToolCall
    | ToolGated
    | ToolResult
    | Warning
    | ApprovalRequested
    | TurnCompleted
    | TurnFailed
    | TurnInterrupted
    | TurnRated
    | RunDelegated
    | MemoryRecapped
    | RoutineFailureHandled
    | SignalReceived
    | WorkspaceReverted;
  sequence: number;
  thread_id: string;
  timestamp: string;
  turn_id: string;
}
export interface ModePinned {
  mode: PermissionMode;
  type: "mode.pinned";
}
export interface TurnStarted {
  message: string;
  model: string;
  origin?: UserOrigin | RoutineOrigin;
  permission_mode?: PermissionMode | null;
  prompt_version?: string | null;
  snapshot?: string | null;
  type: "turn.started";
}
export interface UserOrigin {
  kind: "user";
}
export interface RoutineOrigin {
  delivery_id?: string | null;
  kind: "routine";
  name: string;
  trigger: RoutineTrigger;
}
export interface MessageDelta {
  text: string;
  type: "message.delta";
}
export interface ModelCompleted {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  duration_ms: number;
  input_tokens: number;
  model: string;
  output_tokens: number;
  type: "model.completed";
}
export interface ToolCall {
  arguments: {
    [k: string]: JsonValue;
  };
  call_id: string;
  name: string;
  type: "tool.call";
  write?: boolean | null;
}
export interface ToolGated {
  action: GateOutcome;
  call_id: string;
  decided_by: GateDecider;
  name: string;
  rule: string;
  type: "tool.gated";
}
export interface ToolResult {
  call_id: string;
  duration_ms?: number | null;
  error: boolean;
  name: string;
  output: string;
  type: "tool.result";
}
export interface ApprovalRequested {
  approval_id: string;
  arguments: {
    [k: string]: JsonValue;
  };
  name: string;
  rule: string;
  type: "approval.requested";
}
export interface TurnCompleted {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  input_tokens: number;
  outcome?: CompletionOutcome;
  output_tokens: number;
  snapshot?: string | null;
  type: "turn.completed";
}
export interface TurnFailed {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  code: ErrorCode;
  input_tokens?: number;
  message: string;
  output_tokens?: number;
  snapshot?: string | null;
  type: "turn.failed";
}
export interface TurnInterrupted {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  input_tokens?: number;
  output_tokens?: number;
  snapshot?: string | null;
  type: "turn.interrupted";
}
export interface RunDelegated {
  run: DelegatedRun;
  type: "run.delegated";
}
export interface MemoryRecapped {
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  input_tokens: number;
  model?: string | null;
  node: string | null;
  output_tokens: number;
  type: "memory.recapped";
}
export interface RoutineFailureHandled {
  name: string;
  notice?: RoutineNotice | null;
  type: "routine.failure.handled";
}
export interface SignalReceived {
  delivery: Delivery;
  origin: RoutineOrigin;
  type: "signal.received";
}
export interface Delivery {
  body: string;
  content_type: string;
  delivery_id?: string | null;
  headers: {
    [k: string]: string;
  };
  received_at: string;
}
/**
 * The workspace went from ``previous`` back to ``restored``, the target's before tree.
 */
export interface WorkspaceReverted {
  previous: string;
  restored: string;
  target_turn_id: string;
  type: "workspace.reverted";
}
